FROM balenalib/%%BALENA_ARCH%%-debian-python

RUN install_packages \
    nano \
    i2c-tools \
    kmod \
    libiio0 \
    libiio-utils \
    python3-libiio \
    wireless-tools

WORKDIR /usr/src/app

RUN pip3 install smbus2 paho-mqtt requests

COPY *.py ./

CMD ["python3", "sensor.py"]

